apiVersion: v1
kind: DeploymentConfig
metadata:
  name: hbase
  namespace: hbase
  labels:
    app: hbase
spec:
  triggers:
    - type: ConfigChange'
  replicas: 1
  test: false
  selector:
    app: hbase
    deploymentconfig: hbase
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hbase
        deploymentconfig: hbase

    spec:
      containers:
        - name: hbase
          image: ziccardi/hbase
          ports:
            - containerPort: 2181
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8085
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
            - containerPort: 9095
              protocol: TCP
            - containerPort: 16010
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 1001
